### ISSUE TITLE
Is it still usable ? If yes how ? I don't get it ...

### ISSUE THREAD

**Issue by pierretusseau** [coolacid/slackbot-twitch#10]
Hello,

So I tried to figure out what to do with slack and twitch, now I understand how OutGoingHooks are working, but I still don't know how to use your code, or even if it's usable...

Your features where EXACTLY what I'm looking for, so it's a bit frustrating to not be able to use it :(

**Comment by coolacid** [comment]
This should be still usable by setting up the configuration file. However, I no longer do anything with twich, so this is unsupported.
